name: Sync labels
on:
  pull_request:
    branches: [ $default-branch ]
  push:
    branches: [ $default-branch ]
    paths:
      - '../labels.yml'
jobs:
  lables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
